### ISSUE TITLE
Error in multisite mode.

### ISSUE THREAD

**Issue by hifall** [Perlkonig/grav-plugin-count-views#2]
I am not able to make the knowledge base skeleton to work in multisite mode.

Here is what happens:

First I set up the skeleton in single-site mode:
1 download the skeleton from: https://getgrav.org/downloads/skeletons;
2 upload it to server under /var/www/grav/ and install it as instructed;
3 now it works as expected in single-site mode, that is, browsing to www.mydomain.com/grav/ shows the knowledge base page just fine;

Next set up the grav multi-site mode by taking the subdomain approach as instructed here: https://learn.getgrav.org/advanced/multisite-setup:
1 create a directory sites under grav/user, then create a directory ustc under sites;
2 copy these 4 directories config, pages, plugins, and themes from /var/www/grav/user/ to the ustc directory;
3 create the setup.php file in grav root, and populate it with required code for subdomain;
4 now browse to ustc.mydomain.com/grav/, it is expected to show the knowledge base page, instead, I see:
<img width="635" alt="screen shot 2017-04-15 at 11 26 41 am" src="https://cloud.githubusercontent.com/assets/5734293/25060392/8e6e0412-21ce-11e7-85d6-19706632589e.png">

And here is the stack trace from /var/www/grav/logs/grav.log:
[2017-04-15 22:40:32] grav.CRITICAL: Opening file for writing failed on error fopen(/count-views.yaml): failed to open stream: Permission denied - Trace: #0 /var/www/grav/user/sites/ustc.mydomain.com/plugins/count-views/count-views.php(74): RocketTheme\Toolbox\File\File->lock() #1 [internal function]: Grav\Plugin\CountViewsPlugin->onPageInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #2 /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #4 /var/www/grav/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #5 /var/www/grav/system/src/Grav/Common/Grav.php(272): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/www/grav/system/src/Grav/Common/Processors/PagesProcessor.php(26): Grav\Common\Grav->fireEvent('onPageInitializ...') #7 /var/www/grav/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\PagesProcessor->process() #8 /var/www/grav/system/src/Grav/Common/Grav.php(358): Grav\Common\Grav->Grav\Common\{closure}() #9 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #10 /var/www/grav/system/src/Grav/Common/Grav.php(334): call_user_func_array(Object(Closure), Array) #11 /var/www/grav/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #12 /var/www/grav/index.php(45): Grav\Common\Grav->process() #13 {main} [] []

**Comment by hifall** [comment]
Any idea what's going on?
:)

**Comment by Perlkonig** [comment]
I don't  use multisite and am not familiar with the caveats. The plugin looks in `user/data` for the data  file. If multisite is not supported by the Grav locator, or if `user://data` does not resolve properly under multisite, then the plugin won't work. I'm afraid I simply do not have time to debug this. If you discover the root cause, then I can try to devise a workaround, but I don't have time to learn multisite and track this down myself. I'm sorry.

**Comment by hifall** [comment]
Thanks for your reply.

Would you consider providing paid consultancy to debug this plugin?

Best regards.

**Comment by Perlkonig** [comment]
To clarify, you're not changing the default config of the plugin, right?

**Comment by Perlkonig** [comment]
Does your site folder actually have a `data` subfolder?

**Comment by Perlkonig** [comment]
I ask because I'm told that the code as written (using the Grav locator `user://data`) is supposed to "just work" with multisite.

**Comment by hifall** [comment]
Yes! That is the problem. After I copied the data folder over, things look fine.

Thank you!
